### ISSUE TITLE
运行失败了

### ISSUE THREAD

**Issue by github-yyh** [Hootrix/Yuemiao#2]
↑ **请将上方标题修改为 “头像墙加入归档”** ↑  

### 您的GitHub主页地址：
> https://github.com/{用户名}
![image](https://user-images.githubusercontent.com/54128233/156932561-537a78ee-8fcf-408b-9ae8-55e48b943772.png)
PS C:\Users\yyh\Downloads\Yuemiao-master> python .\Yuemiao.py
九价HPV疫苗
Traceback (most recent call last):
  File "C:\Users\yyh\Downloads\Yuemiao-master\Yuemiao.py", line 170, in <module>
    raise e
  File "C:\Users\yyh\Downloads\Yuemiao-master\Yuemiao.py", line 148, in <module>
    _list = m.seckill_list(city_name=city)
  File "C:\Users\yyh\Downloads\Yuemiao-master\Yuemiao.py", line 64, in seckill_list
    assert list_hospital['ok'] and list_hospital['data']['rows'], ('列表数据错误：%s' % list_hospital['msg'])
AssertionError: 列表数据错误：用户登录超时,请重新登入!

**Comment by Hootrix** [comment]
https://github.com/Hootrix/Yuemiao/blob/master/Yuemiao.py#L134
这个token要自己获取
